const bankInstruments = [
    {idpc: 1  , 	name:"Acoustic Grand Piano"},
    {idpc: 2  , 	name:"Bright Acoustic Piano"},
    {idpc: 3  , 	name:"Electric Grand Piano"},
    {idpc: 4  , 	name:"Honky-tonk Piano"},
    {idpc: 5  , 	name:"Electric Piano 1"},
    {idpc: 6  , 	name:"Electric Piano 2"},
    {idpc: 7  , 	name:"Harpsichord"},
    {idpc: 8  , 	name:"Clavi"},
    {idpc: 9  , 	name:"Celesta"},
    {idpc: 10 , 	name:"Glockenspiel"},
    {idpc: 11 , 	name:"Music Box"},
    {idpc: 12 , 	name:"Vibraphone"},
    {idpc: 13 , 	name:"Marimba"},
    {idpc: 14 , 	name:"Xylophone"},
    {idpc: 15 , 	name:"Tubular Bells"},
    {idpc: 16 , 	name:"Dulcimer"},
    {idpc: 17 , 	name:"Drawbar Organ"},
    {idpc: 18 , 	name:"Percussive Organ"},
    {idpc: 19 , 	name:"Rock Organ"},
    {idpc: 20 , 	name:"Church Organ"},
    {idpc: 21 , 	name:"Reed Organ"},
    {idpc: 22 , 	name:"Accordion"},
    {idpc: 23 , 	name:"Harmonica"},
    {idpc: 24 , 	name:"Tango Accordion"},
    {idpc: 25 , 	name:"Acoustic Guitar (nylon)"},
    {idpc: 26 , 	name:"Acoustic Guitar (steel)"},
    {idpc: 27 , 	name:"Electric Guitar (jazz)"},
    {idpc: 28 , 	name:"Electric Guitar (clean)"},
    {idpc: 29 , 	name:"Electric Guitar (muted)"},
    {idpc: 30 , 	name:"Overdriven Guitar"},
    {idpc: 31 , 	name:"Distortion Guitar"},
    {idpc: 32 , 	name:"Guitar harmonics"},
    {idpc: 33 , 	name:"Acoustic Bass"},
    {idpc: 34 , 	name:"Electric Bass (finger)"},
    {idpc: 35 , 	name:"Electric Bass (pick)"},
    {idpc: 36 , 	name:"Fretless Bass"},
    {idpc: 37 , 	name:"Slap Bass 1"},
    {idpc: 38 , 	name:"Slap Bass 2"},
    {idpc: 39 , 	name:"Synth Bass 1"},
    {idpc: 40 , 	name:"Synth Bass 2"},
    {idpc: 41 , 	name:"Violin"},
    {idpc: 42 , 	name:"Viola"},
    {idpc: 43 , 	name:"Cello"},
    {idpc: 44 , 	name:"Contrabass"},
    {idpc: 45 , 	name:"Tremolo Strings"},
    {idpc: 46 , 	name:"Pizzicato Strings"},
    {idpc: 47 , 	name:"Orchestral Harp"},
    {idpc: 48 , 	name:"Timpani"},
    {idpc: 49 , 	name:"String Ensemble 1"},
    {idpc: 50 , 	name:"String Ensemble 2"},
    {idpc: 51 , 	name:"SynthStrings 1"},
    {idpc: 52 , 	name:"SynthStrings 2"},
    {idpc: 53 , 	name:"Choir Aahs"},
    {idpc: 54 , 	name:"Voice Oohs"},
    {idpc: 55 , 	name:"Synth Voice"},
    {idpc: 56 , 	name:"Orchestra Hit"},
    {idpc: 57 , 	name:"Trumpet"},
    {idpc: 58 , 	name:"Trombone"},
    {idpc: 59 , 	name:"Tuba"},
    {idpc: 60 , 	name:"Muted Trumpet"},
    {idpc: 61 , 	name:"French Horn"},
    {idpc: 62 , 	name:"Brass Section"},
    {idpc: 63 , 	name:"SynthBrass 1"},
    {idpc: 64 , 	name:"SynthBrass 2"},
    {idpc: 65 , 	name:"Soprano Sax"},
    {idpc: 66 , 	name:"Alto Sax"},
    {idpc: 67 , 	name:"Tenor Sax"},
    {idpc: 68 , 	name:"Baritone Sax"},
    {idpc: 69 , 	name:"Oboe"},
    {idpc: 70 , 	name:"English Horn"},
    {idpc: 71 , 	name:"Bassoon"},
    {idpc: 72 , 	name:"Clarinet"},
    {idpc: 73 , 	name:"Piccolo"},
    {idpc: 74 , 	name:"Flute"},
    {idpc: 75 , 	name:"Recorder"},
    {idpc: 76 , 	name:"Pan Flute"},
    {idpc: 77 , 	name:"Blown Bottle"},
    {idpc: 78 , 	name:"Shakuhachi"},
    {idpc: 79 , 	name:"Whistle"},
    {idpc: 80 , 	name:"Ocarina"},
    {idpc: 81 , 	name:"Lead 1 (square)"},
    {idpc: 82 , 	name:"Lead 2 (sawtooth)"},
    {idpc: 83 , 	name:"Lead 3 (calliope)"},
    {idpc: 84 , 	name:"Lead 4 (chiff)"},
    {idpc: 85 , 	name:"Lead 5 (charang)"},
    {idpc: 86 , 	name:"Lead 6 (voice)"},
    {idpc: 87 , 	name:"Lead 7 (fifths)"},
    {idpc: 88 , 	name:"Lead 8 (bass + lead)"},
    {idpc: 89 , 	name:"Pad 1 (new age)"},
    {idpc: 90 , 	name:"Pad 2 (warm)"},
    {idpc: 91 , 	name:"Pad 3 (polysynth)"},
    {idpc: 92 , 	name:"Pad 4 (choir)"},
    {idpc: 93 , 	name:"Pad 5 (bowed)"},
    {idpc: 94 , 	name:"Pad 6 (metallic)"},
    {idpc: 95 , 	name:"Pad 7 (halo)"},
    {idpc: 96 , 	name:"Pad 8 (sweep)"},
    {idpc: 97 , 	name:"FX 1 (rain)"},
    {idpc: 98 , 	name:"FX 2 (soundtrack)"},
    {idpc: 99 , 	name:"FX 3 (crystal)"},
    {idpc: 100, 	name:"FX 4 (atmosphere)"},
    {idpc: 101, 	name:"FX 5 (brightness)"},
    {idpc: 102, 	name:"FX 6 (goblins)"},
    {idpc: 103, 	name:"FX 7 (echoes)"},
    {idpc: 104, 	name:"FX 8 (sci-fi)"},
    {idpc: 105, 	name:"Sitar"},
    {idpc: 106, 	name:"Banjo"},
    {idpc: 107, 	name:"Shamisen"},
    {idpc: 108, 	name:"Koto"},
    {idpc: 109, 	name:"Kalimba"},
    {idpc: 110, 	name:"Bag pipe"},
    {idpc: 111, 	name:"Fidpcdle"},
    {idpc: 112, 	name:"Shanai"},
    {idpc: 113, 	name:"Tinkle Bell"},
    {idpc: 114, 	name:"Agogo"},
    {idpc: 115, 	name:"Steel Drums"},
    {idpc: 116, 	name:"Woodblock"},
    {idpc: 117, 	name:"Taiko Drum"},
    {idpc: 118, 	name:"Melodic Tom"},
    {idpc: 119, 	name:"Synth Drum"},
    {idpc: 120, 	name:"Reverse Cymbal"},
    {idpc: 121, 	name:"Guitar Fret Noise"},
    {idpc: 122, 	name:"Breath Noise"},
    {idpc: 123, 	name:"Seashore"},
    {idpc: 124, 	name:"Bird Tweet"},
    {idpc: 125, 	name:"Telephone Ring"},
    {idpc: 126, 	name:"Helicopter"},
    {idpc: 127, 	name:"Applause"},
    {idpc: 128, 	name:"Gunshot"}
]